version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_HOST_IP}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "topic.EncodedBytes:1:1,topic.DecodedJson:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  asn1_codec:
    build:
      context: .
    ports:
      - "8080:8080"
      - "9090:9090"
    depends_on:
      - kafka
    links:
      - kafka
