version: 2.1

#  Copyright (C) 2018-2020 LEIDOS.
# 
#  Licensed under the Apache License, Version 2.0 (the "License"); you may not
#  use this file except in compliance with the License. You may obtain a copy of
#  the License at
# 
#  http://www.apache.org/licenses/LICENSE-2.0
# 
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations under
#  the License.

jobs:
  build:
    docker:
      - image: 'circleci/openjdk:8u252-jdk'
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Initialize Submodules
          command: |
            set -x
            git submodule init
            git submodule update
      - run:
          name: Set up Docker
          command: |
            set -x
            docker version
            docker-compose version
            sudo apt-get update
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            # sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine
            # sudo rm /usr/local/bin/docker-compose
            curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
            chmod +x docker-compose
            sudo mv docker-compose /usr/local/bin
            sudo apt-get install software-properties-common
            sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
            sudo apt-get update 
      - run:
          name: Instal Deps
          command: |
            sudo apt-get install -qq g++-4.9
            export CXX="g++-4.9"
workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
